### ISSUE TITLE
It displays N/A when the charger is connected.

### ISSUE THREAD

**Issue by yangtaihong59** [halfmexican/battery-usage-wattmeter-extension#13] opened 2024-07-26 03:49 UTC
When an external charger is connected, it shows N/A. I hope it won't display the calculation result when an external charger is connected.

**Comment by halfmexican** [comment] 2024-07-29 20:08
duplicate of #12 
will be fixed when I port the extension to GNOME 47

**Closed as completed by halfmexican** 2024-07-29 20:08 UTC
